name: Flujo_trabajo_Tokens
on:
  push:
    branches: [ "main" ]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Personal Access Token
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PATH_SECRET }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos